# Generated by Django 5.2.6 on 2025-09-27 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_productanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url_1', models.URLField(max_length=1024)),
                ('product_name_1', models.CharField(max_length=512)),
                ('analysis_data_1', models.JSONField()),
                ('product_url_2', models.URLField(max_length=1024)),
                ('product_name_2', models.CharField(max_length=512)),
                ('analysis_data_2', models.JSONField()),
                ('comparison_metrics', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
